# -*- coding: utf-8 -*-
"""Hola, Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb

<img height="60px" src="/img/colab_favicon.ico" align="left" hspace="20px" vspace="5px">

## ¡Te damos la bienvenida a Colaboratory!

Colaboratory es un entorno gratuito de blocs de notas de Jupyter que no requiere configuración y se ejecuta completamente en la nube. Para obtener más información, consulta nuestras [preguntas frecuentes](https://research.google.com/colaboratory/faq.html).
"""

#Cerezo Vargas Marcos

n=int(input("dame el valor del grado que este entre [0,3]: "))
x=float(input("dame el valor de x: "))
f=0
if n==0:
  f=1
elif n==1:
  f=x
elif n==2:
  f=(3*x**2)/2 -0.5
else:
  f=(5*x**3)/2 - (3*x)/2
 
print (f)

